---

- name: "Check {{ pkg.description }} binary already exists"
  stat: path="{{ dir.download }}/{{ pkg.file }}-{{ bases[''+ pkg.name].version }}"
  register: pkg_check

- name: "Downloading {{ pkg.description }} binaries"
  when: not pkg_check.stat.exists
  get_url:
    url: "{{ pkg.url }}/{{ pkg.file }}"
    dest: "{{ dir.download }}/{{ pkg.file }}-{{ bases[''+ pkg.name].version }}"
    validate_certs: False
  environment: "{{ proxy_env }}"
  register: pkg_download

