---

- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- selinux:
    policy: targeted
    state: permissive

- name: stop firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: check_centos_system
  command: "{{ item }}"
  with_items:
    - "setenforce 0"
    - "swapoff -a"

